iNODE_PATH ?= ./node_modules
JS_UGLIFY = $(NODE_PATH)/uglify-js/bin/uglifyjs
JS_TESTER = $(NODE_PATH)/vows/bin/vows
LOCALE ?= en_US
	
all: \
  shapely.js \
  shapely.min.js 
	
# Modify this rule to build your own custom release.
	
.INTERMEDIATE shapely.js: \
  src/start.js \
  shapely.geom.js \
  src/end.js
	
shapely.geom.js: \
  src/geom/geometry.js 
	
	
shapely%js: Makefile
	@rm -f $@
	@cat $(filter %.js,$^) > $@.tmp
	$(JS_UGLIFY) $@.tmp -b indent-level=2 -o $@
	@rm $@.tmp
	@chmod a-w $@

%.min.js: %.js Makefile
	@rm -f $@
	$(JS_UGLIFY) $< -c -m -o $@

clean:
	rm -f d3*.js
