# See the README for installation instructions.

NODE_PATH ?= ./node_modules
JS_COMPILER = $(NODE_PATH)/uglify-js/bin/uglifyjs
JS_TESTER = $(NODE_PATH)/vows/bin/vows

JS_FILES = \
	shapely.js 

all: \
	$(JS_FILES) \
	$(JS_FILES:.js=.min.js) \
	package.json


.INTERMEDIATE shapely.js: \
	src/start.js \
	shapely.geom.js \
	shapely.ops.js \
	src/end.js

shapely.ops.js: \
  src/operations/area.js \
  src/operations/envelope.js \
  src/operations/buffer.js

shapely.geom.js: \
	src/geom/geometry.js	\
	src/geom/point.js	\
	src/geom/line.js	\
	src/geom/polygon.js  



test: all
	@$(JS_TESTER)

%.min.js: %.js Makefile
	@rm -f $@
	$(JS_COMPILER) < $< > $@

shapely.%: Makefile
	@rm -f $@
	cat $(filter %.js,$^) > $@
	@chmod a-w $@

install:
	mkdir -p node_modules
	npm install

clean:
	rm -f shapely*.js
